### PR TITLE
Add consume example.

### PR DESCRIPTION
**Pull request by winding-lines**
Currently it fails with the following error, any clues?

```
[2015-11-03 21:07:44,479] ERROR [Replica Manager on Broker 0]: Error when processing fetch request for partition [my-topic,0] offset -1 from consumer with correlation id 3. Possible cause: Request for offset -1 but we only have log segments in the range 0 to 1. (kafka.server.ReplicaManager)
```

I am using Kafka 0.8.2.1

### CODE REVIEW

**Comment by xitep** [comment]
@winding-lines this looks great! thank you.

i'm back in the working process as of today, so will have less time for kafka-rust, but i'll have a look this evening.

regarding your problem: this seems to be very much the same as @Lingling7 had here as part of #20  (see ~12th comment). after the creation of the new topic, there is no offset for the specified group yet tracked in kafka and [it'll return -1 for the offset](https://github.com/spicavigo/kafka-rust/blob/master/src/consumer.rs#L80), which the `Consumer` will use to start fetching messages and consequently receive the error you experienced.

i believe we could be more clever in the consumer in this situation and have it fall back to the earliest or latest offset available for the specified topic. this behaviour could be an optional configuration to the `Consumer`. i would appreciate if you opened an issue for this as it seems to be a re-occurring surprise for users.

**Comment by xitep** [comment]
@winding-lines i get your example nicely running with this patch against master. it's just a quickly hacked solution to the problem i mentioned before; maybe you find it useful in the meanwhile.

```diff
diff --git a/src/consumer.rs b/src/consumer.rs
index 8165b46..0f185d5 100644
--- a/src/consumer.rs
+++ b/src/consumer.rs
@@ -22,7 +22,7 @@
 //! Consumer implements Iterator.
 
 use std::collections::HashMap;
-use error::Result;
+use error::{Error, Result};
 use utils::{TopicMessage, TopicPartitionOffset};
 use client::KafkaClient;
 
@@ -77,11 +77,41 @@ impl Consumer {
     }
 
     fn fetch_offsets(&mut self) -> Result<()> {
-        let tpos = try!(self.client.fetch_group_topic_offset(self.group.clone(), self.topic.clone()));
+        let mut tpos = try!(self.client.fetch_group_topic_offset(self.group.clone(), self.topic.clone()));
         if self.partitions.len() == 0 {
             self.partitions = self.client.topic_partitions.get(&self.topic).unwrap_or(&vec!()).clone();
         }
-        for tpo in tpos {
+
+        // it might well be that kafka was not tracking any offsets so
+        // far for the specified group
+        {
+            // XXX looks like kafka (0.8.2.1) is sending an error code
+            // (even though it documents it won't:
+            // https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetFetchResponse)
+            let has_missing = tpos.iter().filter(|tpo| tpo.offset == -1).next().is_some();
+            if has_missing {
+                println!("have missing group offset ... will go with the latest ones");
+                // in this is the case we'll try fetching only new
+                // messages (but we might equally well also start
+                // fetching the earliest available messages
+                // XXX this strategy really has to be configurable
+                let new_offs = match try!(self.client.fetch_topic_offset(self.topic.clone(), -1)).remove(&self.topic) {
+                    None => return Err(Error::UnknownTopicOrPartition),
+                    Some(pts) => pts,
+                };
+                // ehm ... not really fast (O(n^2))
+                for tpo in &mut tpos {
+                    if tpo.offset == -1 {
+                        if let Some(new_off) = new_offs.iter().find(|pt| pt.partition == tpo.partition) {
+                            tpo.offset = new_off.offset;
+                            tpo.error = None;
+                        }
+                    }
+                }
+            }
+        }
+
+        for tpo in &tpos {
             if self.partitions.contains(&tpo.partition) {
                 self.offsets.insert(tpo.partition, tpo.offset);
             }
```

**Comment by winding-lines** [comment]
Wow, this is cool :+1: 

I am not sure if we should enable this functionality by default and 'fix' the fetch_offset API call. Maybe it makes more sense to expose as a separate API.

In this particular case I am just looking to get the two examples to work, I feel that they should be self consistent. Let me see if I can figure out the client code on top of the existing library API.

**Comment by winding-lines** [comment]
@xitep I've added a simpler `fetch` example to start with.

**Comment by xitep** [comment]
@winding-lines yes, i agree. we can go with the fetch api example directly. though that will be more complicated. maybe for inspiration, here, i have some code to consume all topics, all partitions from a given kafka instance as fast as possible: https://github.com/xitep/monchan/blob/master/src/main.rs#L182

so far thanks, i'll have a look at your code this evening again.

**Comment by xitep** [comment]
i'm sorry, but i changed my mind in the end. i realized it'll be better to fix the consumer first and use your original example. (i'll polish the previously proposed patch a little bit and will submit a merge request.)

my current point of view is that using `fetch_messages` is intended to be more complex (but powerful) to use than demonstrated in the present pull request.

in particular, `fetch_messages` requires you to specify the topic partition and offset as of which the next available "chunk" of messages should be fetched (i believe the current "chunk" size is up to a 32KB of messages.) but which offset is the right one to specify? zero is certainly a good default for a newly created topic, but in reality the message at the offset `0` might well already not be available any more and, thus, would represent an invalid offset. typically you'd use the [fetch_offsets](http://fauzism.co/rustdoc/kafka/client/struct.KafkaClient.html#method.fetch_offsets) or [fetch_topic_offsets](http://fauzism.co/rustdoc/kafka/client/struct.KafkaClient.html#method.fetch_topic_offset) method to find a valid offset to be passed to `fetch_messages`. the next trouble you'll encounter is tracking which messages you have already consumed, such that calling `fetch_messages` the next time will result in the right messages you are interested in (typically you want to read the next "chunk" of messages, so you'll need to specify the right offset.) as mentioned the [monchan](https://github.com/xitep/monchan/blob/master/src/main.rs#L182) project demonstrates that.

on the other side, the `Consumer` is supposed to be a higher-level api solving the mentioned problems behind the scenes. and i think it would just be the right "getting started" example.

on the other hand, i think it doesn't hurt to have a useful "dump-kafka-topic-(partition-)to-stdout" example - but i'd require it to demonstrate iterating over all of the messages (e.g. calling `fetch_messages` in a loop.) I hope you can understand my point.

**Comment by winding-lines** [comment]
You have more experience with the library, this makes sense.

Marius
---

**Comment by xitep** [comment]
hello @winding-lines why closing this PR. I'd love to have your consumer example in master! :)

**Pull request closed without merging**
