### PR TITLE
Add client_mut function to Consumer

### PR DESCRIPTION
**Pull request by sevagh**
Lets us get a mut client. This helped me when doing `reset_metadata()`. The doc string might need to change, whatever you like.

### CODE REVIEW

**Comment by dead10ck** [comment]
@sevagh published on crates.io as v0.6.2. Thanks again!

**Comment by xitep** [comment]
sorry for the long pause from my side; what exactly is the use-case you are after? in general i believe this change is _not_ "safe". it allows the following (which doesn't really make sense to me):

```
1. c = Consumer::with_topic("topic-a")...
2. c.poll(); ...
3. { let mut cm = c.client_mut(); cm.reset_metadata(); cm.load_metadata("topic-b"); }
4. c.poll();
```

The latter (and any following) call to `.poll` will result in no message - it'll not fail. but the consumer will continue (needlessly) maintaining offsets for "topic-a".

maybe you're use-case/required behaviour can be built in to the consumer implementation directly (i guess it's about reloading partition re-assignments for the consumed topics) or be exposed directly in the consumer's API. generally, i do not favor client code working with the consumer (or producer) and `Client` at the same time. they represent different levels of abstraction that we don't want to couple tightly.

**Comment by sevagh** [comment]
This is the code:

```
fn ...(&mut self) -> {
    loop {
            let msgsets = match self.kafka_consumer.poll() {
                Ok(result) => result,
                Err(kafka::error::Error(kafka::error::ErrorKind::Kafka(KafkaCode::NotLeaderForPartition), _)) => {
                    let mut client = self.inner.client_mut();
                    client.load_metadata_all()?;
                    continue
                }
                Err(ref e) => {
                    error!("kafka poll error: {}", e);
                    continue;
                }
            };
```

There's no real way to do this without `client_mut()`, or without re-creating the consumer in the loop if the topic leader changes.

**Comment by xitep** [comment]
@sevagh many thanks for the example! i think this is exactly what https://github.com/spicavigo/kafka-rust/issues/81 is meant to address. until then we can of course keep the `client_mut` method.

**Pull request merged**
