### PR TITLE
use `native-tls` instead of `openssl`

### PR DESCRIPTION
**Pull request by flier**
to solve #149 

there are some limitation:
- it's hard to impl `Clone` for `Error`
- native-tls only support to load CA in DER format and Cert/PKey in PKCS12 format, sfackler/rust-native-tls#27
- native-tls doesn't support disable verification, sfackler/rust-native-tls#3
- native-tls doesn't support `set_cipher_list`, sfackler/rust-native-tls#4

### CODE REVIEW

**Comment by dead10ck** [comment]
It looks like from the [`native-tls` crate's `README`](https://github.com/sfackler/rust-native-tls#rust-native-tls) that it just uses `openssl` under the hood. So, if the goal of this PR is to eliminate a dependency on pre-existing system packages, I'm not sure how `native-tls` helps us.

**Comment by dead10ck** [comment]
Also, just generally speaking, in the future, it would be helpful to put formatting-only changes into their own individual commits so that the PR is easier to review. :)

**Comment by flier** [comment]
@dead10ck 

`native-tls` will try to use native TLS at OSX (security-framework) and windows (schannel) platform, or they will fallback to openssl.

For example, it is the dependencies on my macbook 

```
kafka v0.5.0
├── byteorder v0.5.3
├── crc v1.4.0
│   └── lazy_static v0.2.8
├── flate2 v0.2.19
│   ├── libc v0.2.22
│   └── miniz-sys v0.1.9
│       └── libc v0.2.22 (*)
├── fnv v1.0.5
├── log v0.3.7
├── native-tls v0.1.2
│   ├── security-framework v0.1.14
│   │   ├── core-foundation v0.2.3
│   │   │   ├── core-foundation-sys v0.2.3
│   │   │   │   └── libc v0.2.22 (*)
│   │   │   └── libc v0.2.22 (*)
│   │   ├── core-foundation-sys v0.2.3 (*)
│   │   ├── libc v0.2.22 (*)
│   │   └── security-framework-sys v0.1.14
│   │       ├── core-foundation-sys v0.2.3 (*)
│   │       └── libc v0.2.22 (*)
│   ├── security-framework-sys v0.1.14 (*)
│   └── tempdir v0.3.5
│       └── rand v0.3.15
│           └── libc v0.2.22 (*)
├── ref_slice v1.1.1
└── snappy v0.4.0
    ├── libc v0.2.22 (*)
    └── snappy-sys v0.1.0
        └── libc v0.2.22 (*)
```

Sorry about the format changes, it seems my editor use `rustfmt` on save.

**Comment by dead10ck** [comment]
Right, and I'm not so sure that I agree that using a different implementation of SSL on every platform is a good idea. I could see it making debugging very difficult in the event something breaks. Also, we can only really test on Mac OS and Linux, so who knows if the Windows build even works. And this doesn't fix the problem for Linux, which should be the first priority platform anyway.

**Comment by dead10ck** [comment]
@xitep what do you think?

**Comment by flier** [comment]
I agree, we need a balance between compatibility and maintainability, if you prefer to only maintain a linux friendly distribution, openssl will be enough.

Or, we could choose to trust the external crate like `native-tls` which provide a cross-platform SSL layer.

Besides, if you need Window integration tests, [AppVeyor](https://www.appveyor.com/) could be a choice, there have a lot of projects migrated to it, like [native-tls did](https://github.com/sfackler/rust-native-tls/blob/master/appveyor.yml).

**Comment by fbernier** [comment]
What about maybe using https://github.com/ctz/rustls so we don't have to deal with openssl?

**Comment by dead10ck** [comment]
@fbernier in concept, that library sounds ideal. However, it is not stable or security audited yet. I think those are likely to be requirements for any user of this library that wants to use `kafka-rust` in production. After some thought about this, in concept, I would be alright with using `native-tls`, but I am concerned about the maintenance cost of adding AppVeyor. I unfortunately don't have enough free time to dedicate to making sure that this crate works on all platforms.

**Comment by sevagh** [comment]
Not sure about the effort involved but can't optional compilation/cargo features help? If we can switch between OpenSSL and rustls.

**Comment by dead10ck** [comment]
@sevagh that's a really good idea. We could use features and conditional compilation to use both. We could use `rustls` by default and have `native-tls` be a feature, or maybe vice versa.

**Comment by jwilm** [comment]
Support for `native-tls` would be great. In addition to using the best/easiest security library on each host, it isolates this project from breaking API changes in the security lib APIs.

**Comment by gklijs** [comment]
https://crates.io/crates/rustls is working with windows now, should we close this, and move to (just) rustls instead?

**Pull request closed without merging**
