### PR TITLE
Fix index of out bounds error

### PR DESCRIPTION
**Pull request by xitep**

### CODE REVIEW

**Comment by xitep** [comment]
@dead10ck here's a small fix i needed to make the tool/example work on a topic with an unreachable partition. may i ask for a review and merge? many thanks in advance.

as an example the output looks like this then:

```
topic                     p-id l-id (l-host)      earliest       latest       (size)
broken_topic               0   -1 ()                   -1           -1          (0)
broken_topic               1    1 (xyz:9092)     56505964     56505964          (0)     
```

**Comment by dead10ck** [comment]
This change seems ok, but doesn't `fetch_offsets` return an `Err` on the first erroneous partition? I wouldn't have thought this code was even reachable if one of the partitions wasn't reachable.

**Comment by xitep** [comment]
many thanks for the feedback! indeed, i forgot about `fetch_offsets` returning an `Err` immediately. i just verified, `fetch_offsets` will not query for erroneous partitions, i.e. partitions without a leader (as seen after having (re-)loaded metadata.) these are [filtered out before making the requests](https://github.com/spicavigo/kafka-rust/blob/master/src/client/mod.rs#L848). in fact, i am now more convinced that our difficult decision [back then](https://github.com/spicavigo/kafka-rust/pull/130) to make `fetch_offsets` return `Err` was correct - it strongly signals a point where (all?) metadata should be reloaded by the client.

**Comment by xitep** [comment]
many thanks @dead10ck, i'll merge it.

**Pull request merged**
